### ISSUE TITLE
Issue when loading the gz file to your web app

### ISSUE THREAD

**Issue by waldirio** [samatild/LinuxAiOPerf#12]
Hello,

I'm facing some issues when loading the `.gz` file to your application, the compacted file was created by the script, I can extract and check the content with no issues. However, when selecting the `.gz` file and clicking on `Upload`, I can see the message below.
```
Something Went Wrong!

An unexpected error has occurred during the upload. Please review the following guidelines:
Guidelines:

    Your tarball contents do not match server requirements.
    Are you uploading the correct report?
    Ensure that you are running the latest version.
    Tarball should be generated from the collector script.
    Instructions on how to collect data can be found [here](https://github.com/samatild/LinuxAiOPerf#how-to-collect-data-capture).
```

**Comment by waldirio** [comment]
Hello,

btw, is there any other project that you are sharing the content of the webapp that you are hosting? That one it's also pretty interesting and I'm sure that we can improve it.

Thank you for your work as well! Congrats++
Waldirio

**Comment by samatild** [comment]
Yeah, as initially assumed:
Issue from #9 causing a missing file on the report.

Fixed on script release 1.8 issues by #13  by forcing output files to be created before the start of actual captures. 

@waldirio  feel free to re-open this one if it still doesn't work after testing with 1.8

**Comment by waldirio** [comment]
Hello @samatild 

Thank you for the heads up.

Tested in the latest version
```
# ./linux_aio_perfcheck.sh --version
Linux All-in-One Performance Collector, version 1.8
```

When loading the new gz file in the webapp
```
Something Went Wrong!

An unexpected error has occurred during the upload. Please review the following guidelines:
Guidelines:

    Your tarball contents do not match server requirements.
    Are you uploading the correct report?
    Ensure that you are running the latest version.
    Tarball should be generated from the collector script.
    Instructions on how to collect data can be found [here](https://github.com/samatild/LinuxAiOPerf#how-to-collect-data-capture).
```

Thank you!
Waldirio

**Comment by waldirio** [comment]
Hello,

Btw, I can't reopen your issue, I believe only you can do it.

Thank you!
Waldirio

**Comment by samatild** [comment]
found an issue on how web app processes the uploaded files, implemented a small band-aid :) hope it works
