### ISSUE TITLE
[BUG] Collector Script / Web App - web crash

### ISSUE THREAD

**Issue by jriveralivaque** [samatild/LinuxAiOPerf#30]
**Issue with (chose one)**
[] Collector Script
[X ] Using the WebApp

**Describe the issue**
When I upload the information to review what was extracted by the script, the website crashes, giving error 524

**Steps to reproduce the behavior:**
1. Did this
I upload the information to review what was extracted by the script

**Expected behavior**
show report

**Screenshots**
![image](https://github.com/samatild/LinuxAiOPerf/assets/42852702/74ebbb47-85d3-490d-aecb-156bed940b9c)

**Are you ok sharing your *.tar.gz report with the developer? (private upload link will follow):**
No

**Additional context**

**Comment by samatild** [comment]
@jriveralivaque  hi , thanks for reporting.
- How big is the file that you are uploading ?
- What browser are you using? I recommend using Firefox for files bigger than 10Mb

I uploaded a couple of reports today to the web app and it's working.

**Comment by jriveralivaque** [comment]
hi @samatild ,
How big is the file that you are uploading ?
60MB
What browser are you using? I recommend using Firefox for files bigger than 10Mb
yes, I use Firefox and google Chrome

**Comment by samatild** [comment]
@jriveralivaque , I have updated the web app to improve longer runs.

- Increased Gunicorn server worker timeout from 120s to 300s (5 minutes). Eventually this would give additional time for the report to build.
- Collision protection for automatic delete cycle


Can you retry? I just uploaded a ~90Mb file and it worked with no issues.
If it fails, please let me know the timestamp of the error code from cloud flare so I can dig some server logs

cheers
