### ISSUE TITLE
yum history

### ISSUE THREAD

**Issue by waldirio** [samatild/LinuxAiOPerf#9]
Hello,

I can see that you are collecting yum history from the log file

```
    # Function to check the last package update timestamp on RHEL/CentOS
    check_rhel_last_update() {
        grep -oP "Installed: \K.*" /var/log/yum.log | tail -1 >> $outputdir/yum-history.txt
    }
```

Maybe, in this section, you can also add the command `yum history`. This will cover both scenarios, when testing your app, I didn't get any history, because I tested on rhel8 and there is no `/var/log/yum.log`, instead, I can see `/var/log/dnf.log*`

Maybe, you can improve and collect the info from both sources, `yum history` and also `grep -oP "Installed: \K.*" /var/log/dnf.log*`

Thank you!
Waldirio

**Comment by samatild** [comment]
This might be causing the issue of #12 where we are missing files from tarball
I will add your suggestions to capture additional package data. It's actual a very good idea to have the yum history command output as it provides the dates where packages got installed, thanks for the hint!
